import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button } from 'primereact/button';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className="text-center">
      <Button className="!bg-red-700 !border-red-400 "  label="Click" icon="pi pi-plus"></Button>
            <div className="text-2xl text-gray-800 mt-2">teste</div>
        </div>
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
